api/urls.py
from django.urls import path

urlpatterns = [
    # path(),
]

base/urls.py
from django.urls import path

urlpatterns = [
    # path(),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('', include('base.urls')),
    path('', include('web.urls')),
    path('api/', include('api.urls')),
    path('user/', include('users.urls')),
    path('scrapper/', include('scrapper.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapper/urls.py
from django.urls import path

urlpatterns = [
    # path(),
]

users/urls.py
from django.urls import path

urlpatterns = [
    # path(),
]

web/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('results', views.result_links_view, name='result_links'),
    path('check/<str:batch>/<int:semester>', views.registration_no, name='registration_input'),
    path('check/Default.aspx',
         lambda request: redirect(request.META.get('HTTP_REFERER')) if request else redirect('web:home')),
    path('ranks', views.ranks, name='ranks'),
    path('ranks/<str:batch>/<str:branch>', views.rank_page, name='batch_rank'),
]

api/models.py
from django.db import models

# Create your models here.

base/models.py
from django.db import models

# Create your models here.

scrapper/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.shortcuts import render

# Create your views here.

scrapper/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

web/views.py
from django.shortcuts import render


def home(request):
    context = {"title": "Home"}
    return render(request, 'base/homepage.html', context)


def result_links_view(request):
    result_links_data = [
        ('2016-2020', {1: '#', 2: '#', 3: '#', 4: '#', 5: '#', 6: '#', 7: '#', 8: '#'}),
        ('2017-2021', {1: '#', 2: '#', 3: '#', 4: '#', 5: '#', 6: '#'}),
        ('2018-2022', {1: '#', 2: '#', 3: '#', 4: '#'}),
        ('2019-2023', {1: '#', 2: '#'})
    ]
    context = {
        "title": "Results",
        "result_links_data": result_links_data,
    }
    return render(request, 'web/result_links.html', context)


def registration_no(request, batch, semester):
    context = {
        'batch': batch,
        'semester': semester,
    }

    if request.method == 'GET':
        return render(request, 'web/input_registration_no.html', context=context)

    elif request.method == 'POST':
        reg_no = request.POST['reg']
        year = batch[2:4]
        file = f"results/{year}sem{semester}/{reg_no}.html"
        return render(request, file, context=context)


def ranks(request):
    rank_links_data = [
        (batch, ['CIVIL', 'CSE', 'EEE', 'MECH'])
        for batch in ["2016-2020", "2017-2021", "2018-2022", "2019-2023"]
    ]
    context = {
        "title": "Rank",
        "rank_links_data": rank_links_data,
        "rank_link_page": True
    }
    return render(request, 'web/rank_links.html', context)


branch_code_map = {
    "CIVIL": 101,
    "MECH": 102,
    "EEE": 110,
    "CSE": 105
}


def rank_page(request, batch, branch):
    version = 1.0
    context = {
        "batch": batch,
        "branch": branch,
        "version": version,
        "data_path": f"ranks/data/126-{batch[:4]}-{branch_code_map[branch]}.csv"
    }
    return render(request, 'web/data_table.html', context=context)

base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {#    <link rel="shortcut icon" type="image/png" href="https://picsum.photos/30/30"/>#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>
        {% if title %}{{ title }}{% else %}AKU Bihar {% endif %}
    </title>
    {#    <!-- Dark Mode Begin -->#}
    {#    <style>#}
    {#        body {#}
    {#            color: #eee;#}
    {#            background: #323232;#}
    {#        }#}
    {##}
    {#        body a {#}
    {#            color: #809fff;#}
    {#        }#}
    {#    </style>#}
    {#    <!-- Dark Mode End -->#}
    <style>
        body {
            color: #333;
            background-color: #dddddd;
        }

        body a {
            color: #809fff
        }
    </style>
    {% block head %}
    {% endblock head %}
</head>
<body>
{% include 'base/navbar.html' %}
{% include 'base/messages.html' %}
{% block content %}

{% endblock content %}
{% include 'base/footer.html' %}
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
{% block js %}

{% endblock js %}
</html>


base/templates/base/footer.html
{#<style>#}
{#.footer {#}
{#   position: relative;#}
{#   left: 0;#}
{#   bottom: 0;#}
{#    margin-top: 10px;#}
{#   width: 100%;#}
{#   background-color: red;#}
{#   color: black;#}
{#   text-align: center;#}
{#}#}
{#</style>#}

<style>
    body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
        justify-content: flex-start;
    }

    .footer {
        margin-top: auto;
    }
</style>
<footer class="footer bg-light text-center text-lg-start">

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.3);">
        Developed by <a class="text-dark" target="_blank" href="https://robinsdeepak.in"><strong>Deepak</strong></a>
        with &#10084
    </div>

    <!-- Copyright -->
</footer>

base/templates/base/homepage.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <div class="container" style="padding-top: 1rem;">

        <div class="row justify-content-center" style="width: 100%;">
            <div class="card text-center mb-3 mr-1 ml-1" style="width: 18rem;">
                <div class="card-header font-weight-bold">
                    Results
                </div>
                <div class="card-body">
                    <img src="{% static 'images/medical-results.svg' %}" width="100px" alt="">

                    <h5 class="card-title">Semester Results</h5>
                    <p class="card-text">Check your AKU Semester results. (Only B.Tech Students)</p>
                    <a href="{% url 'web:result_links' %}" class="btn btn-outline-primary">Check Results</a>
                </div>
            </div>


            <div class="card text-center mb-3 mr-1 ml-1" style="width: 18rem;">
                <div class="card-header font-weight-bold">Ranks</div>
                <div class="card-body">
                    <img src="{% static 'images/statistics.svg' %}" width="100px" alt="">

                    <h5 class="card-title">University Ranks</h5>
                    <p class="card-text">Check your semester wise University and College Rank.</p>
                    <a href="{% url 'web:ranks' %}" class="btn btn-outline-primary">Check Your Rank</a>
                </div>
            </div>


            <div class="card text-center mb-3 mr-1 ml-1" style="width: 18rem;">
                <div class="card-header font-weight-bold">Analysis</div>
                <div class="card-body">
                    <img src="{% static 'images/stadistics.svg' %}" width="100px" alt="">
                    <h5 class="card-title">Result Analysis</h5>
                    <p class="card-text">Visualize your performance across college and university.</p>
                    <a href="#" class="btn btn-outline-primary">Go</a>
                </div>
            </div>

            <div class="card text-center mb-3 mr-1 ml-1" style="width: 18rem;">
                <div class="card-header font-weight-bold">Syllabus</div>
                <div class="card-body">
                    <img src="{% static 'images/clipboard.svg' %}" width="100px" alt="">

                    <h5 class="card-title">University Syllabus</h5>
                    <p class="card-text">Semester wise syllabus of all branches for AKU.</p>
                    <a href="#" class="btn btn-outline-primary">Go</a>
                </div>
            </div>
            <div class="card text-center mb-3 mr-1 ml-1" style="width: 18rem;">
                <div class="card-header font-weight-bold">Study Materials</div>
                <div class="card-body">
                    <img src="{% static 'images/study.svg' %}" width="100px" alt="">

                    <h5 class="card-title">Book/Notes and Videos</h5>
                    <p class="card-text">Here you can find and upload some great study materials for your semester
                        exam.</p>
                    <a href="#" class="btn btn-outline-primary">Go</a>
                </div>
            </div>
        </div>
        <div class="alert alert-warning " role="alert" style="text-align: center">
            <h6 class="alert-heading">Would you like to contribute to this website?</h6>
            <hr>
            <p class="mb-0">
{#                This website is not finished yet. I have stopped updating it multiple times but, amount of#}
{#                traffic and request of students compelled me to update it one more time. If you are interested in#}
{#                learning Web Scrapping, Python Automation, Django or Front End Development, this website can be a great#}
{#                place to build something along with your learning. #}
                Drop an email at <a href="mailto:mail@bcepatna.tk?subject=Query"
                   style="text-decoration:none; color: black"><b>mail@bcepatna.tk</b></a> for your queries.</p>
        </div>
    </div>
{% endblock content %}

base/templates/base/messages.html
<div class="container mt-1">
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
</div>

base/templates/base/navbar.html
{% load static %}
<!-- Navbar Begins -->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ccc; width: 100%">
    <a class="navbar-brand" href="{% url 'web:home' %}">AKUBihar</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="{% url 'web:home' %}">Home <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="#">Link</a>#}
{#            </li>#}
        </ul>
    </div>
</nav>

web/templates/web/data_table.html
{% extends 'base/base.html' %}
{% load static %}
{% block head %}

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

    <style>
        body {
            color: #333;
            background-color: #FFFFFF;
        }

        body a {
            color: transparent;
        }
    </style>
{% endblock head %}
{% block content %}

    <div class="container-fluid pt-2">
        <div id='table-container'></div>
    </div>

{% endblock content %}

{% block js %}

    <script type="text/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script type="text/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script type="text/javascript" src="{% static 'table/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'table/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'table/js/jquery.csv.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'table/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="{% static 'table/js/dataTables.bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'table/js/csv_to_html_table.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

    <script>
        CsvToHtmlTable.init({
            csv_path: "{% static data_path %}?version={{ version }}",
            element: 'table-container',
            allow_download: false,
            csv_options: {separator: ',', delimiter: '"'},
            datatables_options: {"paging": false},
            {#custom_formatting: [[4, format_link]]#}
        });
    </script>
{% endblock js %}

web/templates/web/input_registration_no.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container search-form" style="margin-top: 5%;">
        <div class="row justify-content-center">
            <div class="col-sm-6" style="text-align: center; width: 100%;">
                <span>Check your {{ semester }} SEM result here.</span>
                <br>
                <span>B.Tech {{ batch }}</span>
            </div>
        </div>
        <div class="row justify-content-center" style="width: 100%; margin: 10px;">
            <div class="col-sm-6">

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input id="reg" type="text" class="form-control vBigIntegerField " id="formGroupExampleInput" name="reg"
                               placeholder="Registration Number" required>
                    </div>
                    <div class="button" style="text-align: center;">
                        <button id="myButton" type="submit" class="btn btn-outline-secondary">Get Your result</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}


{% block js %}

{% endblock js %}

web/templates/web/rank_links.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container justify-content-center mt-3" style="padding-left: 2rem; padding-right: 2rem;">
        <div class="accordion" id="accordionExample">
            {% for batch, branchs in rank_links_data %}
                <div class="card mb-1 border-0" style="background-color: #dddddd">
                    <div class="row justify-content-center ">
                        <button class="btn btn-block" type="button" data-toggle="collapse"
                                data-target="#collapse_{{ forloop.counter }}"
                                aria-expanded="true" aria-controls="collapse_{{ forloop.counter }}">
                            {{ batch }}
                        </button>
                    </div>
                    <div id="collapse_{{ forloop.counter }}" class="collapse"
                         aria-labelledby="heading_{{ forloop.counter }}"
                         data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="container">
                                {% for branch in branchs %}
                                    <div class="row justify-content-center mb-1 font-weight-bold"
                                         style="background-color: #eeeeee;border: .1px solid grey; border-radius: 5rem;">
                                        <a class="btn btn-block"
                                           href="{% url 'web:batch_rank' batch branch %}"
                                           type="button">
                                            BRANCH: {{ branch }}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

web/templates/web/result_links.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container justify-content-center mt-3" style="padding-left: 2rem; padding-right: 2rem;">
        <div class="accordion" id="accordionExample">
            {% for batch, semesters in result_links_data %}
                <div class="card mb-1">
                    <div class="row justify-content-center ">
                        <button class="btn btn-block" type="button" data-toggle="collapse"
                                data-target="#collapse_{{ forloop.counter }}"
                                aria-expanded="true" aria-controls="collapse_{{ forloop.counter }}">
                            {{ batch }}
                        </button>
                    </div>
                    <div id="collapse_{{ forloop.counter }}" class="collapse"
                         aria-labelledby="heading_{{ forloop.counter }}"
                         data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="container">
                                {% for semester in semesters %}
                                    <div class="row justify-content-center mb-1"
                                         style="background-color: #dddddd;border: .1px solid grey; border-radius: 1rem;">
                                        <a class="btn btn-link" href="{{ semesters.semester }}"
                                           type="button">
                                            SEMESTER: {{ semester }}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}